import type { Hospital } from "./types";

export const sampleHospitals: Hospital[] = [
  {
    PlaceId: "sample-1",
    Title: "New York-Presbyterian Hospital",
    PlaceType: "Hospital",
    Address: {
      Label: "525 E 68th St, New York, NY 10065",
      Street: "525 E 68th St",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10065",
      Country: "USA",
    },
    Position: [-73.9558, 40.7656],
    category: "Hospital",
    phoneNumber: "(212) 746-5454",
    specialty: "General Medicine",
  },
  {
    PlaceId: "sample-2",
    Title: "Mount Sinai Hospital",
    PlaceType: "Hospital",
    Address: {
      Label: "1 Gustave L. Levy Pl, New York, NY 10029",
      Street: "1 Gustave L. Levy Pl",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10029",
      Country: "USA",
    },
    Position: [-73.9536, 40.7891],
    category: "Hospital",
    phoneNumber: "(212) 241-6500",
    specialty: "Cardiology",
  },
  {
    PlaceId: "sample-3",
    Title: "Lenox Hill Hospital",
    PlaceType: "Hospital",
    Address: {
      Label: "100 E 77th St, New York, NY 10075",
      Street: "100 E 77th St",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10075",
      Country: "USA",
    },
    Position: [-73.9581, 40.7756],
    category: "Hospital",
    phoneNumber: "(212) 434-2000",
    specialty: "Orthopedics",
  },
  {
    PlaceId: "sample-4",
    Title: "NYU Langone Medical Center",
    PlaceType: "Hospital",
    Address: {
      Label: "550 1st Ave, New York, NY 10016",
      Street: "550 1st Ave",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10016",
      Country: "USA",
    },
    Position: [-73.9756, 40.7406],
    category: "Hospital",
    phoneNumber: "(212) 263-7300",
    specialty: "Neurology",
  },
  {
    PlaceId: "sample-5",
    Title: "Cedars-Sinai Medical Center",
    PlaceType: "Hospital",
    Address: {
      Label: "8700 Beverly Blvd, Los Angeles, CA 90048",
      Street: "8700 Beverly Blvd",
      Municipality: "Los Angeles",
      Region: "CA",
      PostalCode: "90048",
      Country: "USA",
    },
    Position: [-118.3833, 34.0736],
    category: "Hospital",
    phoneNumber: "(310) 423-3277",
    specialty: "Cancer Treatment",
  },
  {
    PlaceId: "sample-6",
    Title: "UCLA Medical Center",
    PlaceType: "Hospital",
    Address: {
      Label: "757 Westwood Plaza, Los Angeles, CA 90095",
      Street: "757 Westwood Plaza",
      Municipality: "Los Angeles",
      Region: "CA",
      PostalCode: "90095",
      Country: "USA",
    },
    Position: [-118.4456, 34.0686],
    category: "Hospital",
    phoneNumber: "(310) 825-9111",
    specialty: "Research Hospital",
  },
  {
    PlaceId: "sample-7",
    Title: "Rush University Medical Center",
    PlaceType: "Hospital",
    Address: {
      Label: "1653 W Congress Pkwy, Chicago, IL 60612",
      Street: "1653 W Congress Pkwy",
      Municipality: "Chicago",
      Region: "IL",
      PostalCode: "60612",
      Country: "USA",
    },
    Position: [-87.6711, 41.8747],
    category: "Hospital",
    phoneNumber: "(312) 942-5000",
    specialty: "Emergency Medicine",
  },
  {
    PlaceId: "sample-8",
    Title: "Northwestern Memorial Hospital",
    PlaceType: "Hospital",
    Address: {
      Label: "251 E Huron St, Chicago, IL 60611",
      Street: "251 E Huron St",
      Municipality: "Chicago",
      Region: "IL",
      PostalCode: "60611",
      Country: "USA",
    },
    Position: [-87.6206, 41.8947],
    category: "Hospital",
    phoneNumber: "(312) 926-2000",
    specialty: "Transplant Surgery",
  },
  {
    PlaceId: "sample-9",
    Title: "Johns Hopkins Hospital",
    PlaceType: "Hospital",
    Address: {
      Label: "1800 Orleans St, Baltimore, MD 21287",
      Street: "1800 Orleans St",
      Municipality: "Baltimore",
      Region: "MD",
      PostalCode: "21287",
      Country: "USA",
    },
    Position: [-76.5931, 39.2976],
    category: "Hospital",
    phoneNumber: "(410) 955-5000",
    specialty: "Pediatrics",
  },
  {
    PlaceId: "sample-10",
    Title: "Massachusetts General Hospital",
    PlaceType: "Hospital",
    Address: {
      Label: "55 Fruit St, Boston, MA 02114",
      Street: "55 Fruit St",
      Municipality: "Boston",
      Region: "MA",
      PostalCode: "02114",
      Country: "USA",
    },
    Position: [-71.0706, 42.3631],
    category: "Hospital",
    phoneNumber: "(617) 726-2000",
    specialty: "Trauma Center",
  },
  {
    PlaceId: "sample-11",
    Title: "Cleveland Clinic",
    PlaceType: "Hospital",
    Address: {
      Label: "9500 Euclid Ave, Cleveland, OH 44195",
      Street: "9500 Euclid Ave",
      Municipality: "Cleveland",
      Region: "OH",
      PostalCode: "44195",
      Country: "USA",
    },
    Position: [-81.6206, 41.5028],
    category: "Hospital",
    phoneNumber: "(216) 444-2200",
    specialty: "Cardiac Surgery",
  },
  {
    PlaceId: "sample-12",
    Title: "Mayo Clinic",
    PlaceType: "Hospital",
    Address: {
      Label: "200 1st St SW, Rochester, MN 55905",
      Street: "200 1st St SW",
      Municipality: "Rochester",
      Region: "MN",
      PostalCode: "55905",
      Country: "USA",
    },
    Position: [-92.4661, 44.0225],
    category: "Hospital",
    phoneNumber: "(507) 284-2511",
    specialty: "Diagnostic Medicine",
  },
  {
    PlaceId: "sample-13",
    Title: "Memorial Hermann Hospital",
    PlaceType: "Hospital",
    Address: {
      Label: "6411 Fannin St, Houston, TX 77030",
      Street: "6411 Fannin St",
      Municipality: "Houston",
      Region: "TX",
      PostalCode: "77030",
      Country: "USA",
    },
    Position: [-95.3931, 29.7106],
    category: "Hospital",
    phoneNumber: "(713) 704-4000",
    specialty: "Level 1 Trauma",
  },
  {
    PlaceId: "sample-15",
    Title: "City Urgent Care Center",
    PlaceType: "Urgent Care",
    Address: {
      Label: "456 Broadway, Los Angeles, CA 90013",
      Street: "456 Broadway",
      Municipality: "Los Angeles",
      Region: "CA",
      PostalCode: "90013",
      Country: "USA",
    },
    Position: [-118.2437, 34.0522],
    category: "Urgent Care",
    phoneNumber: "(213) 555-5678",
    specialty: "Walk-in Care",
  },
  {
    PlaceId: "sample-18",
    Title: "ExpressCare Urgent Care",
    PlaceType: "Urgent Care",
    Address: {
      Label: "654 Pine St, Houston, TX 77002",
      Street: "654 Pine St",
      Municipality: "Houston",
      Region: "TX",
      PostalCode: "77002",
      Country: "USA",
    },
    Position: [-95.3698, 29.7604],
    category: "Urgent Care",
    phoneNumber: "(713) 555-7890",
    specialty: "Minor Injuries",
  },
  // NYC Hospitals (21-40)
  {
    PlaceId: "sample-21",
    Title: "Bellevue Hospital Center",
    PlaceType: "Hospital",
    Address: {
      Label: "462 1st Ave, New York, NY 10016",
      Street: "462 1st Ave",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10016",
      Country: "USA",
    },
    Position: [-73.9775, 40.7394],
    category: "Hospital",
    phoneNumber: "(212) 562-4141",
    specialty: "Public Hospital",
  },
  {
    PlaceId: "sample-22",
    Title: "St. Luke's Hospital",
    PlaceType: "Hospital",
    Address: {
      Label: "1111 Amsterdam Ave, New York, NY 10025",
      Street: "1111 Amsterdam Ave",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10025",
      Country: "USA",
    },
    Position: [-73.9644, 40.8069],
    category: "Hospital",
    phoneNumber: "(212) 523-4000",
    specialty: "General Medicine",
  },
  {
    PlaceId: "sample-23",
    Title: "Montefiore Medical Center",
    PlaceType: "Hospital",
    Address: {
      Label: "111 E 210th St, Bronx, NY 10467",
      Street: "111 E 210th St",
      Municipality: "Bronx",
      Region: "NY",
      PostalCode: "10467",
      Country: "USA",
    },
    Position: [-73.8781, 40.8803],
    category: "Hospital",
    phoneNumber: "(718) 920-4321",
    specialty: "Academic Medical Center",
  },
  {
    PlaceId: "sample-24",
    Title: "Memorial Sloan Kettering",
    PlaceType: "Hospital",
    Address: {
      Label: "1275 York Ave, New York, NY 10065",
      Street: "1275 York Ave",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10065",
      Country: "USA",
    },
    Position: [-73.9556, 40.7647],
    category: "Hospital",
    phoneNumber: "(212) 639-2000",
    specialty: "Cancer Treatment",
  },
  {
    PlaceId: "sample-25",
    Title: "Weill Cornell Medical Center",
    PlaceType: "Hospital",
    Address: {
      Label: "525 E 68th St, New York, NY 10065",
      Street: "525 E 68th St",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10065",
      Country: "USA",
    },
    Position: [-73.9553, 40.7652],
    category: "Hospital",
    phoneNumber: "(212) 746-5454",
    specialty: "Academic Medicine",
  },
  {
    PlaceId: "sample-26",
    Title: "Columbia University Medical Center",
    PlaceType: "Hospital",
    Address: {
      Label: "622 W 168th St, New York, NY 10032",
      Street: "622 W 168th St",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10032",
      Country: "USA",
    },
    Position: [-73.9442, 40.8419],
    category: "Hospital",
    phoneNumber: "(212) 305-2500",
    specialty: "Research Hospital",
  },
  {
    PlaceId: "sample-27",
    Title: "NYC Health + Hospitals/Harlem",
    PlaceType: "Hospital",
    Address: {
      Label: "506 Lenox Ave, New York, NY 10037",
      Street: "506 Lenox Ave",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10037",
      Country: "USA",
    },
    Position: [-73.9425, 40.8131],
    category: "Hospital",
    phoneNumber: "(212) 939-1000",
    specialty: "Public Hospital",
  },
  {
    PlaceId: "sample-28",
    Title: "NYC Health + Hospitals/Metropolitan",
    PlaceType: "Hospital",
    Address: {
      Label: "1901 1st Ave, New York, NY 10029",
      Street: "1901 1st Ave",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10029",
      Country: "USA",
    },
    Position: [-73.9472, 40.7894],
    category: "Hospital",
    phoneNumber: "(212) 423-6262",
    specialty: "Public Hospital",
  },
  {
    PlaceId: "sample-29",
    Title: "Hospital for Special Surgery",
    PlaceType: "Hospital",
    Address: {
      Label: "535 E 70th St, New York, NY 10021",
      Street: "535 E 70th St",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10021",
      Country: "USA",
    },
    Position: [-73.9561, 40.7681],
    category: "Hospital",
    phoneNumber: "(212) 606-1000",
    specialty: "Orthopedics",
  },
  {
    PlaceId: "sample-30",
    Title: "NYC Health + Hospitals/Elmhurst",
    PlaceType: "Hospital",
    Address: {
      Label: "79-01 Broadway, Elmhurst, NY 11373",
      Street: "79-01 Broadway",
      Municipality: "Elmhurst",
      Region: "NY",
      PostalCode: "11373",
      Country: "USA",
    },
    Position: [-73.8831, 40.7403],
    category: "Hospital",
    phoneNumber: "(718) 334-4000",
    specialty: "Public Hospital",
  },
  {
    PlaceId: "sample-31",
    Title: "Maimonides Medical Center",
    PlaceType: "Hospital",
    Address: {
      Label: "4802 10th Ave, Brooklyn, NY 11219",
      Street: "4802 10th Ave",
      Municipality: "Brooklyn",
      Region: "NY",
      PostalCode: "11219",
      Country: "USA",
    },
    Position: [-73.9969, 40.6381],
    category: "Hospital",
    phoneNumber: "(718) 283-6000",
    specialty: "Community Hospital",
  },
  {
    PlaceId: "sample-33",
    Title: "NYC Health + Hospitals/Kings County",
    PlaceType: "Hospital",
    Address: {
      Label: "451 Clarkson Ave, Brooklyn, NY 11203",
      Street: "451 Clarkson Ave",
      Municipality: "Brooklyn",
      Region: "NY",
      PostalCode: "11203",
      Country: "USA",
    },
    Position: [-73.9442, 40.6561],
    category: "Hospital",
    phoneNumber: "(718) 245-3131",
    specialty: "Public Hospital",
  },
  {
    PlaceId: "sample-35",
    Title: "NYC Health + Hospitals/Queens",
    PlaceType: "Hospital",
    Address: {
      Label: "82-68 164th St, Jamaica, NY 11432",
      Street: "82-68 164th St",
      Municipality: "Jamaica",
      Region: "NY",
      PostalCode: "11432",
      Country: "USA",
    },
    Position: [-73.8003, 40.7142],
    category: "Hospital",
    phoneNumber: "(718) 883-3000",
    specialty: "Public Hospital",
  },
  {
    PlaceId: "sample-36",
    Title: "NYC Health + Hospitals/Lincoln",
    PlaceType: "Hospital",
    Address: {
      Label: "234 E 149th St, Bronx, NY 10451",
      Street: "234 E 149th St",
      Municipality: "Bronx",
      Region: "NY",
      PostalCode: "10451",
      Country: "USA",
    },
    Position: [-73.9264, 40.8192],
    category: "Hospital",
    phoneNumber: "(718) 579-5000",
    specialty: "Public Hospital",
  },
  {
    PlaceId: "sample-37",
    Title: "NYC Health + Hospitals/Jacobi",
    PlaceType: "Hospital",
    Address: {
      Label: "1400 Pelham Pkwy S, Bronx, NY 10461",
      Street: "1400 Pelham Pkwy S",
      Municipality: "Bronx",
      Region: "NY",
      PostalCode: "10461",
      Country: "USA",
    },
    Position: [-73.8508, 40.8503],
    category: "Hospital",
    phoneNumber: "(718) 918-5000",
    specialty: "Public Hospital",
  },
  {
    PlaceId: "sample-38",
    Title: "NYC Health + Hospitals/Coney Island",
    PlaceType: "Hospital",
    Address: {
      Label: "2601 Ocean Pkwy, Brooklyn, NY 11235",
      Street: "2601 Ocean Pkwy",
      Municipality: "Brooklyn",
      Region: "NY",
      PostalCode: "11235",
      Country: "USA",
    },
    Position: [-73.9611, 40.5856],
    category: "Hospital",
    phoneNumber: "(718) 616-3000",
    specialty: "Public Hospital",
  },
  {
    PlaceId: "sample-39",
    Title: "NYC Health + Hospitals/Woodhull",
    PlaceType: "Hospital",
    Address: {
      Label: "760 Broadway, Brooklyn, NY 11206",
      Street: "760 Broadway",
      Municipality: "Brooklyn",
      Region: "NY",
      PostalCode: "11206",
      Country: "USA",
    },
    Position: [-73.9442, 40.7003],
    category: "Hospital",
    phoneNumber: "(718) 963-8000",
    specialty: "Public Hospital",
  },
  {
    PlaceId: "sample-40",
    Title: "NYC Health + Hospitals/North Central Bronx",
    PlaceType: "Hospital",
    Address: {
      Label: "3424 Kossuth Ave, Bronx, NY 10467",
      Street: "3424 Kossuth Ave",
      Municipality: "Bronx",
      Region: "NY",
      PostalCode: "10467",
      Country: "USA",
    },
    Position: [-73.8847, 40.8781],
    category: "Hospital",
    phoneNumber: "(718) 519-5000",
    specialty: "Public Hospital",
  },
  // NYC Clinics (41-60)
  {
    PlaceId: "sample-41",
    Title: "Manhattan Family Health Center",
    PlaceType: "Clinic",
    Address: {
      Label: "55 W 125th St, New York, NY 10027",
      Street: "55 W 125th St",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10027",
      Country: "USA",
    },
    Position: [-73.9475, 40.8069],
    category: "Clinic",
    phoneNumber: "(212) 423-2000",
    specialty: "Family Medicine",
  },
  {
    PlaceId: "sample-42",
    Title: "East Side Medical Clinic",
    PlaceType: "Clinic",
    Address: {
      Label: "215 E 68th St, New York, NY 10065",
      Street: "215 E 68th St",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10065",
      Country: "USA",
    },
    Position: [-73.9603, 40.7681],
    category: "Clinic",
    phoneNumber: "(212) 555-2001",
    specialty: "Primary Care",
  },
  {
    PlaceId: "sample-43",
    Title: "West Side Community Clinic",
    PlaceType: "Clinic",
    Address: {
      Label: "620 Columbus Ave, New York, NY 10024",
      Street: "620 Columbus Ave",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10024",
      Country: "USA",
    },
    Position: [-73.9769, 40.7894],
    category: "Clinic",
    phoneNumber: "(212) 555-2002",
    specialty: "Community Health",
  },
  {
    PlaceId: "sample-44",
    Title: "Midtown Medical Associates",
    PlaceType: "Clinic",
    Address: {
      Label: "200 W 57th St, New York, NY 10019",
      Street: "200 W 57th St",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10019",
      Country: "USA",
    },
    Position: [-73.9806, 40.7656],
    category: "Clinic",
    phoneNumber: "(212) 555-2003",
    specialty: "Internal Medicine",
  },
  {
    PlaceId: "sample-45",
    Title: "Lower East Side Health Center",
    PlaceType: "Clinic",
    Address: {
      Label: "55 Delancey St, New York, NY 10002",
      Street: "55 Delancey St",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10002",
      Country: "USA",
    },
    Position: [-73.9903, 40.7175],
    category: "Clinic",
    phoneNumber: "(212) 555-2004",
    specialty: "Community Health",
  },
  {
    PlaceId: "sample-46",
    Title: "Upper East Side Medical Group",
    PlaceType: "Clinic",
    Address: {
      Label: "1100 Park Ave, New York, NY 10128",
      Street: "1100 Park Ave",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10128",
      Country: "USA",
    },
    Position: [-73.9531, 40.7831],
    category: "Clinic",
    phoneNumber: "(212) 555-2005",
    specialty: "Primary Care",
  },
  {
    PlaceId: "sample-47",
    Title: "Chelsea Medical Center",
    PlaceType: "Clinic",
    Address: {
      Label: "200 8th Ave, New York, NY 10011",
      Street: "200 8th Ave",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10011",
      Country: "USA",
    },
    Position: [-73.9981, 40.7442],
    category: "Clinic",
    phoneNumber: "(212) 555-2006",
    specialty: "General Practice",
  },
  {
    PlaceId: "sample-48",
    Title: "Greenwich Village Health Clinic",
    PlaceType: "Clinic",
    Address: {
      Label: "12 W 12th St, New York, NY 10011",
      Street: "12 W 12th St",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10011",
      Country: "USA",
    },
    Position: [-73.9969, 40.7347],
    category: "Clinic",
    phoneNumber: "(212) 555-2007",
    specialty: "Family Medicine",
  },
  {
    PlaceId: "sample-49",
    Title: "SoHo Medical Associates",
    PlaceType: "Clinic",
    Address: {
      Label: "150 Spring St, New York, NY 10012",
      Street: "150 Spring St",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10012",
      Country: "USA",
    },
    Position: [-73.9986, 40.7231],
    category: "Clinic",
    phoneNumber: "(212) 555-2008",
    specialty: "Primary Care",
  },
  {
    PlaceId: "sample-50",
    Title: "Tribeca Health Center",
    PlaceType: "Clinic",
    Address: {
      Label: "200 Hudson St, New York, NY 10013",
      Street: "200 Hudson St",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10013",
      Country: "USA",
    },
    Position: [-74.0081, 40.7203],
    category: "Clinic",
    phoneNumber: "(212) 555-2009",
    specialty: "General Practice",
  },
  {
    PlaceId: "sample-51",
    Title: "Brooklyn Heights Medical Clinic",
    PlaceType: "Clinic",
    Address: {
      Label: "100 Henry St, Brooklyn, NY 11201",
      Street: "100 Henry St",
      Municipality: "Brooklyn",
      Region: "NY",
      PostalCode: "11201",
      Country: "USA",
    },
    Position: [-73.9969, 40.6969],
    category: "Clinic",
    phoneNumber: "(718) 555-2010",
    specialty: "Family Medicine",
  },
  {
    PlaceId: "sample-52",
    Title: "Williamsburg Health Center",
    PlaceType: "Clinic",
    Address: {
      Label: "200 Bedford Ave, Brooklyn, NY 11211",
      Street: "200 Bedford Ave",
      Municipality: "Brooklyn",
      Region: "NY",
      PostalCode: "11211",
      Country: "USA",
    },
    Position: [-73.9569, 40.7142],
    category: "Clinic",
    phoneNumber: "(718) 555-2011",
    specialty: "Community Health",
  },
  {
    PlaceId: "sample-53",
    Title: "Park Slope Medical Group",
    PlaceType: "Clinic",
    Address: {
      Label: "300 7th Ave, Brooklyn, NY 11215",
      Street: "300 7th Ave",
      Municipality: "Brooklyn",
      Region: "NY",
      PostalCode: "11215",
      Country: "USA",
    },
    Position: [-73.9781, 40.6681],
    category: "Clinic",
    phoneNumber: "(718) 555-2012",
    specialty: "Primary Care",
  },
  {
    PlaceId: "sample-54",
    Title: "Astoria Medical Clinic",
    PlaceType: "Clinic",
    Address: {
      Label: "2501 31st St, Astoria, NY 11102",
      Street: "2501 31st St",
      Municipality: "Astoria",
      Region: "NY",
      PostalCode: "11102",
      Country: "USA",
    },
    Position: [-73.9264, 40.7703],
    category: "Clinic",
    phoneNumber: "(718) 555-2013",
    specialty: "General Practice",
  },
  {
    PlaceId: "sample-55",
    Title: "Flushing Health Center",
    PlaceType: "Clinic",
    Address: {
      Label: "136-20 38th Ave, Flushing, NY 11354",
      Street: "136-20 38th Ave",
      Municipality: "Flushing",
      Region: "NY",
      PostalCode: "11354",
      Country: "USA",
    },
    Position: [-73.8303, 40.7581],
    category: "Clinic",
    phoneNumber: "(718) 555-2014",
    specialty: "Family Medicine",
  },
  {
    PlaceId: "sample-56",
    Title: "Bronx Community Health Center",
    PlaceType: "Clinic",
    Address: {
      Label: "1000 Grand Concourse, Bronx, NY 10451",
      Street: "1000 Grand Concourse",
      Municipality: "Bronx",
      Region: "NY",
      PostalCode: "10451",
      Country: "USA",
    },
    Position: [-73.9203, 40.8256],
    category: "Clinic",
    phoneNumber: "(718) 555-2015",
    specialty: "Community Health",
  },
  {
    PlaceId: "sample-57",
    Title: "Staten Island Medical Clinic",
    PlaceType: "Clinic",
    Address: {
      Label: "200 Bay St, Staten Island, NY 10301",
      Street: "200 Bay St",
      Municipality: "Staten Island",
      Region: "NY",
      PostalCode: "10301",
      Country: "USA",
    },
    Position: [-74.0781, 40.6417],
    category: "Clinic",
    phoneNumber: "(718) 555-2016",
    specialty: "Primary Care",
  },
  {
    PlaceId: "sample-58",
    Title: "Harlem Medical Associates",
    PlaceType: "Clinic",
    Address: {
      Label: "300 W 125th St, New York, NY 10027",
      Street: "300 W 125th St",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10027",
      Country: "USA",
    },
    Position: [-73.9531, 40.8081],
    category: "Clinic",
    phoneNumber: "(212) 555-2017",
    specialty: "Internal Medicine",
  },
  {
    PlaceId: "sample-59",
    Title: "Washington Heights Health Center",
    PlaceType: "Clinic",
    Address: {
      Label: "600 W 168th St, New York, NY 10032",
      Street: "600 W 168th St",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10032",
      Country: "USA",
    },
    Position: [-73.9425, 40.8419],
    category: "Clinic",
    phoneNumber: "(212) 555-2018",
    specialty: "Family Medicine",
  },
  // NYC Urgent Care (61-75)
  {
    PlaceId: "sample-61",
    Title: "CityMD Upper East Side",
    PlaceType: "Urgent Care",
    Address: {
      Label: "1500 2nd Ave, New York, NY 10075",
      Street: "1500 2nd Ave",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10075",
      Country: "USA",
    },
    Position: [-73.9569, 40.7756],
    category: "Urgent Care",
    phoneNumber: "(212) 555-3001",
    specialty: "Walk-in Care",
  },
  {
    PlaceId: "sample-62",
    Title: "CityMD Midtown",
    PlaceType: "Urgent Care",
    Address: {
      Label: "200 W 42nd St, New York, NY 10036",
      Street: "200 W 42nd St",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10036",
      Country: "USA",
    },
    Position: [-73.9875, 40.7556],
    category: "Urgent Care",
    phoneNumber: "(212) 555-3002",
    specialty: "Urgent Care",
  },
  {
    PlaceId: "sample-63",
    Title: "CityMD Downtown",
    PlaceType: "Urgent Care",
    Address: {
      Label: "100 Broadway, New York, NY 10005",
      Street: "100 Broadway",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10005",
      Country: "USA",
    },
    Position: [-74.0111, 40.7075],
    category: "Urgent Care",
    phoneNumber: "(212) 555-3003",
    specialty: "Walk-in Care",
  },
  {
    PlaceId: "sample-64",
    Title: "CityMD Chelsea",
    PlaceType: "Urgent Care",
    Address: {
      Label: "250 7th Ave, New York, NY 10001",
      Street: "250 7th Ave",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10001",
      Country: "USA",
    },
    Position: [-73.9931, 40.7506],
    category: "Urgent Care",
    phoneNumber: "(212) 555-3004",
    specialty: "Urgent Care",
  },
  {
    PlaceId: "sample-65",
    Title: "CityMD Upper West Side",
    PlaceType: "Urgent Care",
    Address: {
      Label: "200 Amsterdam Ave, New York, NY 10023",
      Street: "200 Amsterdam Ave",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10023",
      Country: "USA",
    },
    Position: [-73.9806, 40.7781],
    category: "Urgent Care",
    phoneNumber: "(212) 555-3005",
    specialty: "Walk-in Care",
  },
  {
    PlaceId: "sample-66",
    Title: "CityMD SoHo",
    PlaceType: "Urgent Care",
    Address: {
      Label: "100 Spring St, New York, NY 10012",
      Street: "100 Spring St",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10012",
      Country: "USA",
    },
    Position: [-73.9986, 40.7231],
    category: "Urgent Care",
    phoneNumber: "(212) 555-3006",
    specialty: "Urgent Care",
  },
  {
    PlaceId: "sample-67",
    Title: "CityMD Brooklyn Heights",
    PlaceType: "Urgent Care",
    Address: {
      Label: "150 Montague St, Brooklyn, NY 11201",
      Street: "150 Montague St",
      Municipality: "Brooklyn",
      Region: "NY",
      PostalCode: "11201",
      Country: "USA",
    },
    Position: [-73.9969, 40.6947],
    category: "Urgent Care",
    phoneNumber: "(718) 555-3007",
    specialty: "Walk-in Care",
  },
  {
    PlaceId: "sample-68",
    Title: "CityMD Williamsburg",
    PlaceType: "Urgent Care",
    Address: {
      Label: "250 Bedford Ave, Brooklyn, NY 11211",
      Street: "250 Bedford Ave",
      Municipality: "Brooklyn",
      Region: "NY",
      PostalCode: "11211",
      Country: "USA",
    },
    Position: [-73.9569, 40.7142],
    category: "Urgent Care",
    phoneNumber: "(718) 555-3008",
    specialty: "Urgent Care",
  },
  {
    PlaceId: "sample-69",
    Title: "CityMD Park Slope",
    PlaceType: "Urgent Care",
    Address: {
      Label: "350 7th Ave, Brooklyn, NY 11215",
      Street: "350 7th Ave",
      Municipality: "Brooklyn",
      Region: "NY",
      PostalCode: "11215",
      Country: "USA",
    },
    Position: [-73.9781, 40.6681],
    category: "Urgent Care",
    phoneNumber: "(718) 555-3009",
    specialty: "Walk-in Care",
  },
  {
    PlaceId: "sample-70",
    Title: "CityMD Astoria",
    PlaceType: "Urgent Care",
    Address: {
      Label: "3000 31st St, Astoria, NY 11102",
      Street: "3000 31st St",
      Municipality: "Astoria",
      Region: "NY",
      PostalCode: "11102",
      Country: "USA",
    },
    Position: [-73.9264, 40.7703],
    category: "Urgent Care",
    phoneNumber: "(718) 555-3010",
    specialty: "Urgent Care",
  },
  {
    PlaceId: "sample-71",
    Title: "CityMD Flushing",
    PlaceType: "Urgent Care",
    Address: {
      Label: "136-30 38th Ave, Flushing, NY 11354",
      Street: "136-30 38th Ave",
      Municipality: "Flushing",
      Region: "NY",
      PostalCode: "11354",
      Country: "USA",
    },
    Position: [-73.8303, 40.7581],
    category: "Urgent Care",
    phoneNumber: "(718) 555-3011",
    specialty: "Walk-in Care",
  },
  {
    PlaceId: "sample-72",
    Title: "CityMD Bronx",
    PlaceType: "Urgent Care",
    Address: {
      Label: "1100 Grand Concourse, Bronx, NY 10451",
      Street: "1100 Grand Concourse",
      Municipality: "Bronx",
      Region: "NY",
      PostalCode: "10451",
      Country: "USA",
    },
    Position: [-73.9203, 40.8256],
    category: "Urgent Care",
    phoneNumber: "(718) 555-3012",
    specialty: "Urgent Care",
  },
  {
    PlaceId: "sample-73",
    Title: "CityMD Staten Island",
    PlaceType: "Urgent Care",
    Address: {
      Label: "300 Bay St, Staten Island, NY 10301",
      Street: "300 Bay St",
      Municipality: "Staten Island",
      Region: "NY",
      PostalCode: "10301",
      Country: "USA",
    },
    Position: [-74.0781, 40.6417],
    category: "Urgent Care",
    phoneNumber: "(718) 555-3013",
    specialty: "Walk-in Care",
  },
  {
    PlaceId: "sample-74",
    Title: "CityMD Harlem",
    PlaceType: "Urgent Care",
    Address: {
      Label: "400 W 125th St, New York, NY 10027",
      Street: "400 W 125th St",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10027",
      Country: "USA",
    },
    Position: [-73.9531, 40.8081],
    category: "Urgent Care",
    phoneNumber: "(212) 555-3014",
    specialty: "Urgent Care",
  },
  {
    PlaceId: "sample-75",
    Title: "CityMD Washington Heights",
    PlaceType: "Urgent Care",
    Address: {
      Label: "700 W 168th St, New York, NY 10032",
      Street: "700 W 168th St",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10032",
      Country: "USA",
    },
    Position: [-73.9425, 40.8419],
    category: "Urgent Care",
    phoneNumber: "(212) 555-3015",
    specialty: "Walk-in Care",
  },
  // NYC Pharmacies (76-90)
  {
    PlaceId: "sample-76",
    Title: "CVS Pharmacy Upper East Side",
    PlaceType: "Pharmacy",
    Address: {
      Label: "1400 1st Ave, New York, NY 10075",
      Street: "1400 1st Ave",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10075",
      Country: "USA",
    },
    Position: [-73.9569, 40.7756],
    category: "Pharmacy",
    phoneNumber: "(212) 555-4001",
    specialty: "Pharmacy",
  },
  {
    PlaceId: "sample-77",
    Title: "CVS Pharmacy Midtown",
    PlaceType: "Pharmacy",
    Address: {
      Label: "250 W 42nd St, New York, NY 10036",
      Street: "250 W 42nd St",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10036",
      Country: "USA",
    },
    Position: [-73.9875, 40.7556],
    category: "Pharmacy",
    phoneNumber: "(212) 555-4002",
    specialty: "Pharmacy",
  },
  {
    PlaceId: "sample-79",
    Title: "Walgreens Upper West Side",
    PlaceType: "Pharmacy",
    Address: {
      Label: "250 Amsterdam Ave, New York, NY 10023",
      Street: "250 Amsterdam Ave",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10023",
      Country: "USA",
    },
    Position: [-73.9806, 40.7781],
    category: "Pharmacy",
    phoneNumber: "(212) 555-4004",
    specialty: "Pharmacy",
  },
  {
    PlaceId: "sample-80",
    Title: "Walgreens SoHo",
    PlaceType: "Pharmacy",
    Address: {
      Label: "150 Spring St, New York, NY 10012",
      Street: "150 Spring St",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10012",
      Country: "USA",
    },
    Position: [-73.9986, 40.7231],
    category: "Pharmacy",
    phoneNumber: "(212) 555-4005",
    specialty: "Pharmacy",
  },
  {
    PlaceId: "sample-81",
    Title: "Duane Reade Brooklyn Heights",
    PlaceType: "Pharmacy",
    Address: {
      Label: "200 Montague St, Brooklyn, NY 11201",
      Street: "200 Montague St",
      Municipality: "Brooklyn",
      Region: "NY",
      PostalCode: "11201",
      Country: "USA",
    },
    Position: [-73.9969, 40.6947],
    category: "Pharmacy",
    phoneNumber: "(718) 555-4006",
    specialty: "Pharmacy",
  },
  {
    PlaceId: "sample-82",
    Title: "Duane Reade Williamsburg",
    PlaceType: "Pharmacy",
    Address: {
      Label: "300 Bedford Ave, Brooklyn, NY 11211",
      Street: "300 Bedford Ave",
      Municipality: "Brooklyn",
      Region: "NY",
      PostalCode: "11211",
      Country: "USA",
    },
    Position: [-73.9569, 40.7142],
    category: "Pharmacy",
    phoneNumber: "(718) 555-4007",
    specialty: "Pharmacy",
  },
  {
    PlaceId: "sample-83",
    Title: "Rite Aid Park Slope",
    PlaceType: "Pharmacy",
    Address: {
      Label: "400 7th Ave, Brooklyn, NY 11215",
      Street: "400 7th Ave",
      Municipality: "Brooklyn",
      Region: "NY",
      PostalCode: "11215",
      Country: "USA",
    },
    Position: [-73.9781, 40.6681],
    category: "Pharmacy",
    phoneNumber: "(718) 555-4008",
    specialty: "Pharmacy",
  },
  {
    PlaceId: "sample-85",
    Title: "Walgreens Flushing",
    PlaceType: "Pharmacy",
    Address: {
      Label: "136-40 38th Ave, Flushing, NY 11354",
      Street: "136-40 38th Ave",
      Municipality: "Flushing",
      Region: "NY",
      PostalCode: "11354",
      Country: "USA",
    },
    Position: [-73.8303, 40.7581],
    category: "Pharmacy",
    phoneNumber: "(718) 555-4010",
    specialty: "Pharmacy",
  },
  {
    PlaceId: "sample-88",
    Title: "Rite Aid Harlem",
    PlaceType: "Pharmacy",
    Address: {
      Label: "500 W 125th St, New York, NY 10027",
      Street: "500 W 125th St",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10027",
      Country: "USA",
    },
    Position: [-73.9531, 40.8081],
    category: "Pharmacy",
    phoneNumber: "(212) 555-4013",
    specialty: "Pharmacy",
  },
  {
    PlaceId: "sample-89",
    Title: "CVS Pharmacy Washington Heights",
    PlaceType: "Pharmacy",
    Address: {
      Label: "800 W 168th St, New York, NY 10032",
      Street: "800 W 168th St",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10032",
      Country: "USA",
    },
    Position: [-73.9425, 40.8419],
    category: "Pharmacy",
    phoneNumber: "(212) 555-4014",
    specialty: "Pharmacy",
  },
  {
    PlaceId: "sample-90",
    Title: "Walgreens Chelsea",
    PlaceType: "Pharmacy",
    Address: {
      Label: "300 7th Ave, New York, NY 10001",
      Street: "300 7th Ave",
      Municipality: "New York",
      Region: "NY",
      PostalCode: "10001",
      Country: "USA",
    },
    Position: [-73.9931, 40.7506],
    category: "Pharmacy",
    phoneNumber: "(212) 555-4015",
    specialty: "Pharmacy",
  },
  // Additional locations from other cities (91-100)
  {
    PlaceId: "sample-91",
    Title: "Kaiser Permanente Los Angeles",
    PlaceType: "Hospital",
    Address: {
      Label: "4867 Sunset Blvd, Los Angeles, CA 90027",
      Street: "4867 Sunset Blvd",
      Municipality: "Los Angeles",
      Region: "CA",
      PostalCode: "90027",
      Country: "USA",
    },
    Position: [-118.2931, 34.0981],
    category: "Hospital",
    phoneNumber: "(323) 783-4011",
    specialty: "HMO Hospital",
  },
  {
    PlaceId: "sample-92",
    Title: "USC Medical Center",
    PlaceType: "Hospital",
    Address: {
      Label: "1500 San Pablo St, Los Angeles, CA 90033",
      Street: "1500 San Pablo St",
      Municipality: "Los Angeles",
      Region: "CA",
      PostalCode: "90033",
      Country: "USA",
    },
    Position: [-118.2069, 34.0603],
    category: "Hospital",
    phoneNumber: "(323) 442-8500",
    specialty: "Academic Medical Center",
  },
  {
    PlaceId: "sample-94",
    Title: "University of Chicago Medical Center",
    PlaceType: "Hospital",
    Address: {
      Label: "5841 S Maryland Ave, Chicago, IL 60637",
      Street: "5841 S Maryland Ave",
      Municipality: "Chicago",
      Region: "IL",
      PostalCode: "60637",
      Country: "USA",
    },
    Position: [-87.6069, 41.7881],
    category: "Hospital",
    phoneNumber: "(773) 702-1000",
    specialty: "Academic Medical Center",
  },
  {
    PlaceId: "sample-95",
    Title: "Brigham and Women's Hospital",
    PlaceType: "Hospital",
    Address: {
      Label: "75 Francis St, Boston, MA 02115",
      Street: "75 Francis St",
      Municipality: "Boston",
      Region: "MA",
      PostalCode: "02115",
      Country: "USA",
    },
    Position: [-71.1069, 42.3356],
    category: "Hospital",
    phoneNumber: "(617) 732-5500",
    specialty: "Academic Medical Center",
  },
  {
    PlaceId: "sample-96",
    Title: "Beth Israel Deaconess Medical Center",
    PlaceType: "Hospital",
    Address: {
      Label: "330 Brookline Ave, Boston, MA 02215",
      Street: "330 Brookline Ave",
      Municipality: "Boston",
      Region: "MA",
      PostalCode: "02215",
      Country: "USA",
    },
    Position: [-71.1081, 42.3397],
    category: "Hospital",
    phoneNumber: "(617) 667-7000",
    specialty: "Academic Medical Center",
  },
  {
    PlaceId: "sample-97",
    Title: "University of Texas MD Anderson",
    PlaceType: "Hospital",
    Address: {
      Label: "1515 Holcombe Blvd, Houston, TX 77030",
      Street: "1515 Holcombe Blvd",
      Municipality: "Houston",
      Region: "TX",
      PostalCode: "77030",
      Country: "USA",
    },
    Position: [-95.4014, 29.7075],
    category: "Hospital",
    phoneNumber: "(713) 792-2121",
    specialty: "Cancer Treatment",
  },
  {
    PlaceId: "sample-98",
    Title: "Baylor St. Luke's Medical Center",
    PlaceType: "Hospital",
    Address: {
      Label: "6720 Bertner Ave, Houston, TX 77030",
      Street: "6720 Bertner Ave",
      Municipality: "Houston",
      Region: "TX",
      PostalCode: "77030",
      Country: "USA",
    },
    Position: [-95.3981, 29.7103],
    category: "Hospital",
    phoneNumber: "(832) 355-1000",
    specialty: "Academic Medical Center",
  },
  {
    PlaceId: "sample-99",
    Title: "University of Pennsylvania Hospital",
    PlaceType: "Hospital",
    Address: {
      Label: "3400 Spruce St, Philadelphia, PA 19104",
      Street: "3400 Spruce St",
      Municipality: "Philadelphia",
      Region: "PA",
      PostalCode: "19104",
      Country: "USA",
    },
    Position: [-75.1931, 39.9481],
    category: "Hospital",
    phoneNumber: "(215) 662-4000",
    specialty: "Academic Medical Center",
  },
  {
    PlaceId: "sample-100",
    Title: "Thomas Jefferson University Hospital",
    PlaceType: "Hospital",
    Address: {
      Label: "111 S 11th St, Philadelphia, PA 19107",
      Street: "111 S 11th St",
      Municipality: "Philadelphia",
      Region: "PA",
      PostalCode: "19107",
      Country: "USA",
    },
    Position: [-75.1581, 39.9503],
    category: "Hospital",
    phoneNumber: "(215) 955-6000",
    specialty: "Academic Medical Center",
  },
];
